### ISSUE TITLE
Video Library Section

### ISSUE THREAD

**Issue by scanalesrh** [rht-labs/practice-library#108]
New section for all the cool videos supporting practices and labs.
Like this one: https://mojo.redhat.com/videos/936286

**Comment by sherl0cks** [comment]
It would be best to host these on the relevant practice page. I don't think introducing a taxonomy based on content type is in our best interest.

**Comment by sherl0cks** [comment]
In the case of the linked video (which can be found publicly https://www.youtube.com/watch?v=502ILHjX9EE) we should create a product owner practice.

**Comment by scanalesrh** [comment]
Hi, this came from people posting video content in mojo that is already in labs, so maybe a landing page for related video media is a good idea.

**Comment by sherl0cks** [comment]
@scanalesrh I read the thread and @tenfourty 's suggestion on mojo. I'm also aware that we use this video during enablement, though that content is in google slides, its not in the public domain.

RE: a landing page - let's just think through the idea quickly. what happens when we get ~10 videos on that landing page? we need some way to structure them so they make sense to users. I see the logical way to do that structuring along practice lines, and since we have a practice oriented taxonomy already, I'd like to reuse it instead of adding complexity to the library

**Comment by scanalesrh** [comment]
@ sherl0cks I agree avoiding aditional complexity, I just was thinking about having a link between people searching that kind of content and labs, you are totally right, it makes more sence inside a practice line, just wanted to review this idea and have this conversation.

Thanks!

**Comment by sherl0cks** [comment]
sure thing - I've opened https://github.com/rht-labs/practice-library/issues/110 to track the PO practice
